name: Build

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: Update submodules
      run: git submodule update --init --recursive
    - name: Download the third party directory
      run: curl -L 'https://www.dropbox.com/s/0al5rl9afi2al73/libraryFiles.zip?dl=0' --output libraryFiles.zip
    - name: List all files
      run: ls
    - name: Size of zip
      run: du -h libraryFiles.zip   
    - name: Unzip the third party library
      run: unzip libraryFiles.zip -d iMEGA/Vendor/sdk/bindings/ios/3rdparty/
    - name: Move files from libraryFiles folder to its parent directory
      run: mv iMEGA/Vendor/sdk/bindings/ios/3rdparty/libraryFiles/* iMEGA/Vendor/sdk/bindings/ios/3rdparty/ 
    - name: Move to karere directory
      run: cd iMEGA/Vendor/Karere/src/
    - name: List all files
      run: ls
    - name: Run the cmake command on karere directory
      run: cmake -P genDbSchema.cmake
    - name: Return back to main directory
      run: cd /
    - name: Build the project
      run: xcodebuild clean build -workspace "iMEGA.xcworkspace" -scheme "MEGA"



 
